name: network

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ${APP_DATA}/nginx-proxy-manager/data:/data
      - ${APP_DATA}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    labels:
      homepage.group: Network
      homepage.name: Nginx Proxy Manager
      homepage.icon: nginx-proxy-manager.png
      homepage.href: http://nginx.${DOMAIN_NAME}
      homepage.widget.type: npm
      homepage.widget.url: http://${IP_ADDRESS}:81
      homepage.widget.username: ${NPM_USERNAME}
      homepage.widget.password: ${DEFAULT_APP_PASSWORD}
      npm.proxy.domain: nginx.${DOMAIN_NAME}
      npm.proxy.port: "81"

  npm-docker-sync:
    container_name: npm-docker-sync
    image: ghcr.io/redth/npm-docker-sync:latest
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      DOCKER_HOST_IP: ${IP_ADDRESS}
      NPM_URL: http://${IP_ADDRESS}:81
      NPM_EMAIL: ${NPM_USERNAME}
      NPM_PASSWORD: ${DEFAULT_APP_PASSWORD}
      NPM_PROXY_SSL_FORCE: true
      NPM_PROXY_BLOCK_EXPLOITS: true
      NPM_PROXY_WEBSOCKETS: true
      NPM_PROXY_HTTP2: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    depends_on:
      - nginx-proxy-manager

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      # - 3000:3000/tcp
      - 2080:80/tcp
      - 2443:443/tcp
    volumes:
      - ${APP_DATA}/adguardhome/work:/opt/adguardhome/work
      - ${APP_DATA}/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    labels:
      homepage.group: Adguard DNS
      homepage.name: Primary
      homepage.icon: azure-dns.png
      homepage.href: http://adguard.${DOMAIN_NAME}
      homepage.widget.type: adguard
      homepage.widget.url: http://${IP_ADDRESS}:2080
      homepage.widget.username: ${ADGUARD_USERNAME}
      homepage.widget.password: ${DEFAULT_APP_PASSWORD}
      npm.proxy.domain: adguard.${DOMAIN_NAME}
      npm.proxy.port: "2080"

  adguardhome-sync:
    container_name: adguardhome-sync
    image: lscr.io/linuxserver/adguardhome-sync:latest
    ports:
      - 8082:8080
    volumes:
      - ${APP_DATA}/adguardsync:/config
    restart: unless-stopped
    labels:
      npm.proxy.domain: adguard-sync.${DOMAIN_NAME}
      npm.proxy.port: "8082"
    
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: false
      LOG_LEVEL: info
      TZ: ${TZ}
    restart: unless-stopped
