name: network

networks:
  default:
    name: ${NETWORK_NAME}
    external: true

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ${APP_DATA}/nginx-proxy-manager/data:/data
      - ${APP_DATA}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    labels:
      npm.proxy.domain: nginx.${DOMAIN_NAME}
      npm.proxy.port: "81"
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/nginx-proxy-manager.png
      net.unraid.docker.webui: http://nginx.${DOMAIN_NAME}

  npm-docker-sync:
    container_name: npm-docker-sync
    image: ghcr.io/redth/npm-docker-sync:latest
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      DOCKER_HOST_IP: ${IP_ADDRESS}
      NPM_URL: http://${IP_ADDRESS}:81
      NPM_EMAIL: ${NPM_USERNAME}
      NPM_PASSWORD: ${DEFAULT_APP_PASSWORD}
      NPM_PROXY_SSL_FORCE: true
      NPM_PROXY_BLOCK_EXPLOITS: true
      NPM_PROXY_WEBSOCKETS: true
      NPM_PROXY_HTTP2: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    depends_on:
      - nginx-proxy-manager
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/nginx-proxy-manager.png

  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 2080:80/tcp
      - 2443:443/tcp
    volumes:
      - ${APP_DATA}/adguardhome/work:/opt/adguardhome/work
      - ${APP_DATA}/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
    labels:
      npm.proxy.domain: adguard.${DOMAIN_NAME}
      npm.proxy.port: "2080"
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/adguard-home.png
      net.unraid.docker.webui: http://adguard.${DOMAIN_NAME}

  adguardhome-sync:
    container_name: adguardhome-sync
    image: lscr.io/linuxserver/adguardhome-sync:latest
    ports:
      - 8082:8080
    volumes:
      - ${APP_DATA}/adguardsync:/config
    restart: unless-stopped
    labels:
      npm.proxy.domain: adguard-sync.${DOMAIN_NAME}
      npm.proxy.port: "8082"
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/adguard-home.png
      net.unraid.docker.webui: http://adguard-sync.${DOMAIN_NAME}
    
  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    ports:
      - "8191:8191"
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: false
      LOG_LEVEL: info
      TZ: ${TZ}
    restart: unless-stopped
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/flaresolverr.png
